services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python -m textblob.download_corpora"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
  - type: web
    name: react-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
